Добавила две таблицы из своей БД.
Dora201/ConfectioneryFactoryORM pull request #1
Opened 2021-11-14 15:20 UTC by Dora201

Попыталась создать два объекта в классе ConfectioneryFactory.Demo - не получилось. Проекты друг друга "не видят".

2021-11-15 11:53 UTC, MarinaPaley requested changes

2021-11-15 11:53 UTC, MarinaPaley commented on ConfectioneryFactory/ConfectioneryFactory.Domain/Ingredient.cs
> +            Id = id;
`this.Id = id;`

2021-11-15 11:53 UTC, MarinaPaley commented on ConfectioneryFactory/ConfectioneryFactory.Domain/Ingredient.cs
> +
`public virtual ISet<Product> Products = { get; protected set; } = new HashSet<Products>();`

2021-11-15 11:53 UTC, MarinaPaley commented on ConfectioneryFactory/ConfectioneryFactory.Domain/Product.cs
> +            NumOfProducts = numOfProducts;
не ответственность продукта

2021-11-15 11:53 UTC, MarinaPaley commented on ConfectioneryFactory/ConfectioneryFactory.Domain/Product.cs
> +        public Product(int id, string name, string type, int price, int numOfProducts)
Продукт должен зависеть от ингредиентов. т. е. подаем множество ингредиентов

2021-11-15 11:53 UTC, MarinaPaley commented on ConfectioneryFactory/ConfectioneryFactory.Domain/Product.cs
> +        public virtual int NumOfProducts { get; protected set; }
не нужно

2021-11-15 11:53 UTC, MarinaPaley commented on ConfectioneryFactory/ConfectioneryFactory.Domain/Product.cs
> +
`public virtual ISet<Ingredient> Ingredients { get; protected set; } = new HashSet<Ingredients>();`

2021-11-15 11:53 UTC, MarinaPaley commented on ConfectioneryFactory/ConfectioneryFactory.Domain/ConfectioneryFactory.Domain.csproj
> +</Project>
нужно поменть тип проекта на `Dinamic Linked Library`

2021-11-22 08:31 UTC, Dora201 commented
Файл ClassLibrary1 лишний забыла удалить и только сейчас заметила!

2021-11-22 11:48 UTC, MarinaPaley approved these changes

2021-11-22 11:48 UTC, MarinaPaley commented on ConfectioneryFactory/ClassLibrary1/Class1.cs
> +﻿using System;
лишнее

2021-11-22 11:48 UTC, MarinaPaley commented on ConfectioneryFactory/ConfectioneryFactory.Staff/Extensions/StringExtensions.cs
> +            var trimmedValue = value?.Trim(' ', '\n', '\t', '\r', '\0');
здесь вопрос, может не работать

2021-12-05 12:54 UTC, merged